event <- read.csv("./Analysis//Event.csv")
stores <- read.csv("./Analysis//Stores.csv")

storedg <- stores
storedg[is.na(storedg)] <- 0

plot(storedg[,2], type = "l")
plot(storedg[,3], type = "l")
plot(storedg[,4], type = "l")
plot(storedg[,5], type = "l")
plot(storedg[,6], type = "l")
plot(storedg[,7], type = "l")
plot(storedg[,8], type = "l")
plot(storedg[,9], type = "l")
plot(storedg[,10], type = "l")
plot(storedg[,11], type = "l")
plot(storedg[,12], type = "l")
plot(storedg[,13], type = "l")
plot(storedg[,14], type = "l")
plot(storedg[,15], type = "l")
plot(storedg[,16], type = "l")
plot(storedg[,17], type = "l")
plot(storedg[,18], type = "l")
plot(storedg[,19], type = "l")
plot(storedg[,20], type = "l")
plot(storedg[,21], type = "l")
plot(storedg[,22], type = "l")
plot(storedg[,23], type = "l")
plot(storedg[,24], type = "l")
plot(storedg[,25], type = "l")
plot(storedg[,26], type = "l")
plot(storedg[,27], type = "l")
plot(storedg[,28], type = "l")